### ISSUE TITLE
Breaking bug: Comma

### ISSUE THREAD

**Issue by profucius** [ennioitaliano/obsidian-auto-glossary#8] opened 2023-02-02 07:24 UTC
When creating an Index file, any files within the folder that is being Indexed will have what appear to be missing filelinks, if those filenames contained a comma (`,`)

Filename: `File, name`
Intended resulting index: `[[File, name]]`
Actual resulting index: `[[File name]]`

**Comment by ennioitaliano** [comment] 2023-02-02 08:23
That's a duplicate of bug #6 .

**Closed by ennioitaliano** 2023-02-02 08:23 UTC
